import "./globals.css";
import { Inter } from "next/font/google";
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NEXT BLOG APP ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>

            <div className="container">
            <ToastContainer />
              {children}
            </div>
      </body>
    </html>
  );
}